name: Vapor CI with Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Vapor project inside Docker
        run: |
          docker run --rm -v "$(pwd):/workspace" -w /workspace swift:6.0 bash -c "swift build && swift test"
