name: Vapor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Swift
        uses: fwal/setup-swift@v2
        with:
          swift-version: '5.10' # or your current Swift version

      - name: Build project
        run: swift build -v

      - name: Run tests
        run: swift test -v
